

skinparam {
  shadowing false
  roundcorner 10
  ParticipantPadding 20
  BoxPadding 10
  Padding 5
  defaultFontName Yu Gothic UI Bold
}

skinparam Note {
  BackgroundColor #ffffff
  BorderColor #6ea695
  FontColor #000000
}

skinparam sequence {
  ArrowColor #000000

  LifeLineBorderColor #6ea695
  LifeLineBackgroundColor #7BB19A

  ActorBorderColor #000000
  ActorBackgroundColor #ffffff
  ActorFontStyle bold

  GroupBorderThickness 1
  GroupBorderColor #6ea695

  ParticipantBorderColor #6ea695
  ParticipantBackgroundColor #a0cab8
  ParticipantFontColor #000000
}