

skinparam {
  shadowing false
  roundcorner 10
  ParticipantPadding 20
  BoxPadding 10
  Padding 5
  defaultFontName Yu Gothic UI Bold
}

skinparam Note {
  BackgroundColor #ffffff
  BorderColor #0e5a88
  FontColor #000000
}

skinparam sequence {
  ArrowColor #000000

  LifeLineBorderColor #0e5a88
  LifeLineBackgroundColor #7392b9

  ActorBorderColor #000000
  ActorBackgroundColor #ffffff
  ActorFontStyle bold

  GroupBorderThickness 1
  GroupBorderColor #0e5a88

  ParticipantBorderColor #0e5a88
  ParticipantBackgroundColor #9cc0d9
  ParticipantFontColor #000000
}